# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.{build}

# branches to build
branches:
  # whitelist
  only:
    - appveyor

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2015

environment:
  bass_url: http://www.un4seen.com/files/bass24.zip

platform:
  - x86
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  parallel: true
  project: tcview\tcview.sln      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: detailed

# scripts to run before build
before_build:
  - ps: |
      $wc = New-Object System.Net.WebClient
      $wc.DownloadFile($Env:bass_url, "C:/projects/tcview/bass24.zip")
  - 7z x bass24.zip -oc:\projects\tcview\bass24 -r
  - copy /y bass24\c\bass.h tcview\tcview\bass.h
  - copy /y bass24\c\bass.lib tcview\tcview\bass_x86.lib
  - copy /y bass24\c\x64\bass.lib tcview\tcview\bass_x64.lib

# scripts to run after build
after_build:
  - mkdir dist
  - mkdir dist\tcview
  - copy /y tcview\x64\Release\tcview.wlx64 dist\tcview\tcview.wlx64
  - copy /y tcview\Release\tcview.wlx dist\tcview\tcview.wlx
  - copy /y C:\projects\bass24\bass.dll dist\tcview\bass.dll
  - copy /y C:\projects\bass24\x64\bass.dll dist\tcview\bass_x64.dll
  
# to run your custom scripts instead of automatic MSBuild
build_script:

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: dist
    name: TCView
    type: zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider name are case-sensitive!
#deploy:
#  - provider: FTP
#    username: admin
#    password: psw

#  - provider: WebDeploy
#    url: http://www.deploy.com/myendpoint
#    on:
#      branch: release
#      platform: x86
#      configuration: debug

#  - provider: Environment
#    name: staging
#    on:
#      branch: staging
#      environment:
#      var1: value1
#      var2: value2

# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:

# on build failure
on_failure:
