# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.{build}

# branches to build
branches:
  # whitelist
  only:
    - appveyor

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  parallel: true
  project: tcview/tcview.sln      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: detailed

# scripts to run before build
before_build:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

#artifacts:

#  # pushing a single file
#  - path: test.zip

  # pushing a single file with environment variable in path and "Deployment name" specified
#  - path: MyProject\bin\$(configuration)
#    name: myapp

  # pushing entire folder as a zip archive
#  - path: logs

  # pushing all *.nupkg files in directory
#  - path: out\*.nupkg


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider name are case-sensitive!
#deploy:
#  - provider: FTP
#    username: admin
#    password: psw

#  - provider: WebDeploy
#    url: http://www.deploy.com/myendpoint
#    on:
#      branch: release
#      platform: x86
#      configuration: debug

#  - provider: Environment
#    name: staging
#    on:
#      branch: staging
#      environment:
#      var1: value1
#      var2: value2

# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:

# on build failure
on_failure:
